# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Jozo.io
description: "A free Jekyll theme for download"
keywords: "programming, python, software development, blog"
url: https://jozo.io
baseurl: ""

google_analytics: UA-86904557-2
repo: https://github.com/jozo/jozo.github.io
disqus_shortname: "fadawargithubio"
#disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Jozef Gaborik
  job: Python developer
  bio: "Caring about clean code and open-source, always looking for the best project."
  thumb: /images/avatar-j.png
  email: hi@jozo.io
  url: https://jozo.io
  github: https://github.com/jozo
  twitter: https://twitter.com/jozo_io
  facebook: https://facebook.com/jozef.gaborik
  linkedin: https://www.linkedin.com/in/jozo/

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: icons
    title: Icons
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
